### ISSUE TITLE
二段階認証でループしてしまう

### ISSUE THREAD

**Issue by shobobon** [k0kubun/Nocturn#1]
windows版を利用していますが、携帯電話の二段階承認を有効にしていると
何度やってもIDとPasswordの画面にリロードされてしまい利用出来ませんでした

**Comment by r7kamura** [comment]
これ自分の作ってるTwitterクライアントでも過去に発生して対処したの覚えてます

**Comment by r7kamura** [comment]
@k0kubun node-integrationがデフォルトで有効になっていて、これが有効になっていると `module` が存在するのでTwitterで使っているjQueryの解決とかがうまくいかずエラーになってしまうという問題があって、もしそれが原因であればこれを無効化すれば直るはずです。 https://github.com/k0kubun/Nocturn/pull/2 で雑に直してみたんで良かったら試してみてください。

**Comment by k0kubun** [comment]
https://github.com/k0kubun/Nocturn/pull/2 あったほうがよさそうだったのでマージしました

認証画面にこれとは独立のバグ(なぜか2FAじゃなくてもいつのまにかリトライ時に壊れるようになっていた)があって動かないので対応します

**Comment by k0kubun** [comment]
最近僕の電話番号でも2FAができるようになっていたので2FAサポートして v0.1.8でリリースしました :rocket:
