### ISSUE TITLE
list 選択後にアカウント変更すると変更前の list が固定される

### ISSUE THREAD

**Issue by akawshi** [k0kubun/Nocturn#10]
マルチアカウントでともに list を所持している状況でアカウント変更後の list が表示されませんでした

**Comment by k0kubun** [comment]
うーん、僕の環境では問題なく動作しているので、再現手順をより詳細にいただけないでしょうか
あと、再起動などすると挙動は変わりますか？

**Comment by akawshi** [comment]
アカウントで list 表示をし, ある公開 list を選択, 表示後に profile image を選択してアカウント変更しました

アカウントは２つあり, そのどちらも profile image を表示できていない状況だったのでアカウントが選択されたものであるかの確認をするために一度 tweet をし, Timeline で当該 tweet を確認後, 変更後のアカウントで複数の非公開の list から TL を読みこもうと list ボタンを選択したところ, 変更前アカウントの list が表示されました

念の為, Refresh を行ったところ, 変更前アカウントでの list 一覧で同じ数の list の幅が list 表示されない状況, つまり10あるとすれば10あると予定される幅の空欄が表示され, タブ変更でまた従前の list が表示されます

この動作を再起動後も試しましたが, いずれにおいても同じ状況が確認されます。

**Comment by k0kubun** [comment]
なるほど。動かなくてすみません… :bow: 

v0.2.0以上だと、起動時に現在のprofile imageのurlを取得してそれを使うので、表示できないという状況がすでに何かおかしいですね。
リストに関してもprofile imageに関しても状況が再現できていないのですが、考えている原因は4つあって、

- ia32環境だとakawshiさんのアカウントのIDかリストのIDが数値型で処理できる最大を超えている
  - 内部実装の問題です、ツイートは既にそうしてるんですが、ユーザーとかリストもIDを文字列で処理するように直してみます
- Nocturn内部が持っているprofile imageのキャッシュが壊れている
  - その場合はNocturnを一旦完全に消して入れ直すなど
- Nocturnがメモリを使いすぎてメモリが足りなくなり期待通り動作しないか、重すぎて内部で変更が行われる順序が期待と異なってしまっている
  - すみません…
- Nocturnのバージョンが古いか、古いバージョンが生成するjsonが何らかの理由により使われている
  - https://github.com/k0kubun/Nocturn/releases/tag/v0.2.3 を解答してそのまま使うとどうなるでしょうか

**Comment by akawshi** [comment]
Source code からですか....やってみます
古い PC なのでメモリが足りていない状況は恒常的に起こっているとは考えられます。Timeline の取得状況を観察しても, 前後して取得表示している状態がみられますので...

とにかく色々試してみたいとは思います
ありがとうございます

**Comment by k0kubun** [comment]
どもども

> Source code からですか....やってみます

あ、いえ、普通にバイナリが入ってるzipのことです、もうそれで動かしてたらすみません
https://github.com/k0kubun/Nocturn/releases/download/v0.2.3/Nocturn-linux-ia32.zip

**Comment by akawshi** [comment]
v0.2.5 を linux-ia32 から使ってみました
上述の list の空白表示はなくなりました...が, バージョンアップの前と後でアカウント変更をしていないにもかかわらず, 常に 問題の list 一覧が固定され, アカウント変更による list の変更を受け付けないようです

**Comment by k0kubun** [comment]
なるほど、v0.2.5でも確認ありがとうございます

正直これも再現できていないんですが、

> ユーザーとかリストもIDを文字列で処理する

をやれば直るかもしれないので、その対応をしたものをリリースしたら再度お伝えします。

**Comment by akawshi** [comment]
ありがとうございます

**Comment by akawshi** [comment]
timeline の動作を撮影したのでついでに list の方も撮影しておきました
![anim](https://cloud.githubusercontent.com/assets/6780166/13747410/7d2f9380-ea3b-11e5-9559-f5f7c4149f4a.gif)

**Comment by k0kubun** [comment]
わかりやすいです、ありがとうございます

これprofile image出てないのでわかりにくくなってますが、表示されているtimelineもリストも投稿先もも全て2つ目のアカウントで行われているように見えるので、アカウントの切り替えに失敗してるという現象な感じがしますね。
画像が表示できないときは内部のキャッシュが壊れている可能性があって、何らかの方法でキャッシュをクリアする機能を実装しようと思ってます。

ただあまりにも毎度profile imageが表示できてないのは何かがおかしくて、多分保存しておいたユーザーIDを読み出す時にia32だから桁が足りなくて間違ったIDのprofile imageを取得しようとして失敗してるという線が一番可能性が高い&唯一直し方がわかるので、その対応をしたらお伝えします。

**Comment by akawshi** [comment]
いえ, timeline は最初に選択したアカウントの方が準拠で2番目選択のアカウントでも取得してるようです。一部表示がされます
mention も撮影はしてませんがどちらとも取得ができていないようで, 撮影前7時間に2番目のアカウントに送ったものが表示できませんし, 頻繁にやりとりを行う最初のアカウントの方でも表示できない状況です
投稿先に関してはアカウントごとの投稿ができている状態を認めます

**Comment by k0kubun** [comment]
32ビット環境でしか再現しなそうなバグの対策をv0.3.0で入れたのでお試しください。
(また動かなかったらすみません…)
https://github.com/k0kubun/Nocturn/releases/tag/v0.3.0

**Comment by akawshi** [comment]
ありがとうございます
認証がうまくいき, 元通り list が表示されるようになりました

**Comment by k0kubun** [comment]
確認ありがとうございます :+1:
