### ISSUE TITLE
メッセージボックスに f を入力すると active になった timeline 上の tweet が favorite される

### ISSUE THREAD

**Issue by akawshi** [k0kubun/Nocturn#11]
半角 f をメッセージボックスに入力する際に timeline 上で active になった tweet が favorite されるようです

**Comment by k0kubun** [comment]
テキストを入力する欄は2つあってツイートする場所と検索する場所があると思うんですが、メッセージボックスというのは多分ツイートする方ですよね。
だとするとその現象も再現できてないんですが、そのfを入力するときはメッセージボックスにはfは入力されている状態ですか？  fが入力されるのと同時にツイートもfavoriteされて☆に色がつきますか？

これも再現が難しく現象がよくわからないので、できればgifアニメがあると助かります… :bow:

**Comment by akawshi** [comment]
はい, tweet の方ですね

> そのfを入力するときはメッセージボックスにはfは入力されている状態ですか？ fが入力されるのと同時にツイートもfavoriteされて☆に色がつきますか？

その通りになります

**Comment by akawshi** [comment]
こちらですね
![anim](https://cloud.githubusercontent.com/assets/6780166/13779030/636528b8-eafc-11e5-8114-9c8b65f50323.gif)

**Comment by k0kubun** [comment]
gifアニメありがたいです、現象理解しました

というか今確認したら普通に再現しました…これは必ず直します。

**Comment by k0kubun** [comment]
v0.3.0で直しました。 https://github.com/k0kubun/Nocturn/releases/tag/v0.3.0
これは再現できてて直せたのでクローズしちゃいます。動かなかったらreopenしてください
