### ISSUE TITLE
新規使用で二段階認証を行うとログイン画面に戻って来てしまう

### ISSUE THREAD

**Issue by ncaq** [k0kubun/Nocturn#115]
# 起きている現象

新規に使おうと思ってログインしようとしているが、二段階認証を完了するとログイン画面に戻って来てしまい、ループしてしまう。
[二段階認証でループしてしまう · Issue #1 · k0kubun/Nocturn](https://github.com/k0kubun/Nocturn/issues/1)
が関係しているかもしれません。

# 開発者ツールのコンソールログ

~~~
authenticate:7 Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
js_inst?c_name=ui_metrics:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://abs.twimg.com https://abs-0.twimg.com". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ js_inst?c_name=ui_metrics:3
js_inst?c_name=ui_metrics:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://abs.twimg.com https://abs-0.twimg.com". Either the 'unsafe-inline' keyword, a hash ('sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ js_inst?c_name=ui_metrics:3
~~~

authenticateの内容をクリックしてみましたが、空のファイルが表示されました。

# 使ってるVersion

[Release v1.8.4 · k0kubun/Nocturn](https://github.com/k0kubun/Nocturn/releases/tag/v1.8.4)
の
`Nocturn-win32-ia32.zip`

# Windowsのバージョン

エディション	Windows 11 Pro
バージョン	22H2
インストール日	‎2022/‎10/‎03
OS ビルド	22621.675
エクスペリエンス	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by k0kubun** [comment]
私の手元 (Ubuntu 22.04) で二段階認証を使ったログインを試してみましたが、問題なく動作しました。そのため、Nocturn自体のロジックの問題ではなく、Nocturnが使っている何らかのライブラリのWindows特有の問題か、ncaqさんの環境特有の問題ということになろうかと思います。いずれにせよ、こちらで再現できるようになるまでは、ncaqさんに原因を調査していただくか修正していただくしかなさそうです。

頂いたコンソールのログでは具体的にどの部分が壊れているのかわからないのですが、それぞれのメッセージが出ている場所でバックトレース全体をどうにか出していただき、それを共有していただくことはできないでしょうか?

**Comment by ncaq** [comment]
再現しないですか、とりあえず今気力が消失しているので、また機会があったらデバッグします…
