### ISSUE TITLE
Can you guys build a Key Binding for Liking a Tweet?

### ISSUE THREAD

**Issue by MeetThePatel** [k0kubun/Nocturn#13]

**Comment by k0kubun** [comment]
You mean you want to input url like https://twitter.com/foo/status/1234... of focused tweet to textarea by the key binding?

**Comment by MeetThePatel** [comment]
nah, i mean like favouriting a tweet. (its now called liking, i dunno what they were thinking).
I just want a keybinding that favorites the highlighted tweet.

**Comment by k0kubun** [comment]
I think we already have a key binding for favorite, which is <kbd>f</kbd>.
https://github.com/k0kubun/Nocturn#key-bindings

**Comment by MeetThePatel** [comment]
Oh, i couldnt see it, due to the awkward wording
