### ISSUE TITLE
Date sorting is "middle-out"?

### ISSUE THREAD

**Issue by howardjones** [k0kubun/Nocturn#24]
On a fresh install (windows 10/64, v1.2.1) both my accounts show tweets in a strange order, with the first ones being older than the ones below, but then older ones again below that...

The other account is a bit less extreme (a handful of 1h ago, followed by just now, followed by history) but here's an example:

![nocturn-sorting](https://cloud.githubusercontent.com/assets/912421/17379374/15540630-59ba-11e6-94cc-00f7161b295e.png)

**Comment by k0kubun** [comment]
Oh, thanks to report that. Sorting within some years may be broken? I'll research it later.
Is it wrong only on initial loading?

**Comment by k0kubun** [comment]
I guess possibly it was due to https://github.com/k0kubun/Nocturn/commit/aa3bcfab382bbac8f45c24c67e6eef7c3e93fd98. Closing.
