### ISSUE TITLE
a newer windows version?

### ISSUE THREAD

**Issue by sergiuprt** [k0kubun/Nocturn#38]
hey!
i'm currently on windows, but the last version for this os is 1.2.1 :(

**Comment by k0kubun** [comment]
Oops sorry. I've forgotten to install wine on my Linux machine. I'm working on it now. Just a moment please.

**Comment by sergiuprt** [comment]
@k0kubun thanks ^_^

**Comment by k0kubun** [comment]
Released Nocturn v1.2.4 with windows again. Could you try that?

**Comment by sergiuprt** [comment]
using it :)
