### ISSUE TITLE
Bug validate login.

### ISSUE THREAD

**Issue by DaviRamosAndrade** [k0kubun/Nocturn#42]
[
![screenshot from 2016-10-14 18-55-38](https://cloud.githubusercontent.com/assets/5041033/19403909/9c93d94a-9240-11e6-898d-2e03c024b6d3.png)
](url)

**Comment by Equinox** [comment]
Looks like a duplicate of https://github.com/k0kubun/Nocturn/issues/25.

**Comment by k0kubun** [comment]
Fixed this issue on Nocturn v1.4.2. Could you try it?
