### ISSUE TITLE
video doesn't scale in window after new commits

### ISSUE THREAD

**Issue by CandyFace** [k0kubun/Nocturn#46]
Hi

Sweet changes you made to the code, I think I understand somewhat how to do that next time myself.
I noticed though that scaling for video's doesn't work anymore. 

Error says "media-popup.js:42 Uncaught TypeError: Cannot assign to read only property 'videoWidth' of object '#<HTMLVideoElement>"

**Comment by k0kubun** [comment]
Reverted. Still I found another problem. Current master is unstable and difficult to release...
