### ISSUE TITLE
テキストボックス横の自分のアイコンの表示の失敗

### ISSUE THREAD

**Issue by akawshi** [k0kubun/Nocturn#5]
一度自分のアイコンを変更し, 回線のエラーなどでアイコンの取得表示に失敗した場合に変更後のアイコンが表示されず, 画像が読み込めてないアイコンとして表示されます

**Comment by k0kubun** [comment]
ああ、そうなんですよね、アカウント作成時に作ったjsonのurlを読み続けていて、これは開発中のブランチでは直ってるのでもう少ししたら直ります :pray:

**Comment by k0kubun** [comment]
v0.2.0で直しました。 https://github.com/k0kubun/Nocturn/releases/tag/v0.2.0
