### ISSUE TITLE
GNU Social support?

### ISSUE THREAD

**Issue by orta** [k0kubun/Nocturn#62]
With Mastodon (https://mastodon.social) getting [some profile](https://www.google.com/search?hl=en&gl=uk&tbm=nws&authuser=0&q=mastodon&oq=mastodon&gs_l=news-cc.3..43j0l9j43i53.3262.6324.0.6411.12.7.3.2.2.0.175.724.4j3.7.0...0.0...1ac.1.SgHZCDL_sJY) - you may be able to create a great native client for GNU Social based on this.

**Comment by k0kubun** [comment]
That was an interesting suggestion (indeed I didn't know of Mastodon when you filed this), but because I ended up not using Mastodon for a while after knowing it, I decided not to support this for now. I hope there's a good alternative for Mastodon. Thanks.
