### ISSUE TITLE
AUR - Lack of dependencies

### ISSUE THREAD

**Issue by foooomio** [k0kubun/Nocturn#63]
Needs `libxss` and `gconf` as dependency.

**Comment by k0kubun** [comment]
Thanks for the suggestion, but I no longer use Arch Linux and therefore I just disowned the package before. Fortunately it seems another person, FredBezies, did the latest release on behalf of me, so I'm not gonna fix it by myself for now. Please comment about this issue at https://aur.archlinux.org/packages/nocturn/ or talk to the person. Thanks again.
