### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/Nocturn#8]
v2 or later
## features
- [ ] Create configuration window
  - [ ] Migrate add account action
  - [ ] Font size
  - [ ] Allow Ctrl+Enter publish
- [ ] DM
- [ ] Show mention tree
- [ ] Show tweets of the user by double click
- [ ] Show tweet detail
- [ ] Dropdown menu
- [x] Favorites tab
- [ ] Reorder tabs
- [ ] Automatic Streaming refresher
- [ ] Localized relative time
- [x] Set minimum window width
- [ ] Ctrl + Tab binding
- [x] Prevent keybind in authentication window
- [ ] Link hash tag
- [x] Reconnect streaming with refresh
- [ ] Show private mark for users
- [ ] Truncate long url upto 36
- [ ] Notification tab
- [x] Unfavorite
- [ ] Dock badge
- [x] Show image thumbnail
- [x] Ignore self favorite event
- [x] Ignore self mention for notification
- [ ] Upload image
- [x] Add application icon
- [ ] Font change config
## internal
- [ ] Change the way to focus on editor
- [ ] Drop hack for account selector focus
- [x] Drop duplication of implementation to fire action
- [ ] Use react-route or something to invoke action from component in IpcAction
- [x] Minimize react component updates
  - [x] Optimize tweet select performance
- [ ] Drop all document reference
- [ ] Use [i+1] instead of slice(1)[0]
- [ ] Refactor IpcAction, RichState
- [ ] Stop using querySelector
- [x] Drop tab key binder
- [ ] Use browserify or webpack
- [ ] Write tests http://redux.js.org/docs/recipes/WritingTests.html
- [ ] Try react-router 
- [ ] Save tweets by Hash
- [ ] Add interface to return default state
- [x] Drop timeline proxy

**Comment by RayFoss** [comment]
- [ ] Emojii support
- [ ] Emojii keyboard
- [ ] Tray icon
- [ ] Close to tray
- [ ] Linux install script, for a lack of proper/complex deb/rpm build docker.

Possible temporary solution to icon:
https://github.com/RayFoss/Nocturn/commit/aea54d4e8c6bd0ba10b173fb7b9480c2c839ed4d

**Comment by aek** [comment]
Show popup notifications for new tweets like push notifications

**Comment by cirrusUK** [comment]
◻◻⬜⬜⃣  ⬛️⬜⬛️⬜Change backround, foreground & hyperlink colours

**Comment by shwsun** [comment]
I really wish I can change the font size :-)
It makes my eyes hurt now

**Comment by k0kubun** [comment]
I'm resuming maintenance of this project, but this issue looks too huge and apparently I don't have time to handle everything. This should be closed for now and important ones should be filed independently. I'll revisit this when I need to remember some ideas, including your follow-up comments, though. Thank you for your interests.
