### ISSUE TITLE
Timeline の移動ができない

### ISSUE THREAD

**Issue by akawshi** [k0kubun/Nocturn#9]
jk でも矢印操作に於いてもともに timeline 外の tweet への移動が出来なくなってるようです

**Comment by k0kubun** [comment]
timeline外、というのは表示されてる一番古いツイートよりも古いツイートに移動したい、ということですか？

**Comment by akawshi** [comment]
あ, 再度確認したところ移動は行っているようですが, 
表示されている timeline の下にある古い timeline へ移動させた場合に表示がなされないということです
訂正します

**Comment by k0kubun** [comment]
あー、画面外のツイートにフォーカスを移動した時に、フォーカスしているツイートがタイムラインの真ん中に来るような機能を実装しているんですが、それがうまく機能してなくてフォーカスしているツイートが画面外のままっていう感じでしょうか

**Comment by akawshi** [comment]
ちなみに, 上に行く場合でもなりますね...

**Comment by k0kubun** [comment]
これ僕の環境(Arch Linux, OSX El Capitan)だと再現しなくて、いまだに状況がよくわかってないのでもし可能であれば再現している状況をアニメgif画像などでいただけないでしょうか

**Comment by akawshi** [comment]
こちらですね
![anim](https://cloud.githubusercontent.com/assets/6780166/13747037/b4acae62-ea39-11e5-92e7-9483f0b8be99.gif)

**Comment by k0kubun** [comment]
わかりやすくて助かります。やっぱりスクロールするかの判定がおかしいという現象なんですね。これはまだ原因が想像つかないですが、この画面のあと何度jを押しても永遠にスクロールが始まらないですか？画面外ぎりぎりだとスクロールが始まらないもののもう少し下にいけば適切にスクロールされるというのであればちょっと判定を厳しくすれば治りそうなので。

あと本来jkか矢印で画面の外に出たらスクロールされる機能、そもそもこれ自体再現させられてなかったりしますか？

**Comment by akawshi** [comment]
30秒ほど j のみを押した状態で timeline 内の移動を試みましたが, スクロールが起きていないのを確認しました

> jkか矢印で画面の外に出たらスクロールされる機能、そもそもこれ自体再現させられてなかったりしますか？

えっと, 申し訳ないですが, どういうことでしょうか
ちなみに, マウスホイールでの上下移動やスクロールバーを掴むことでの上下移動は可能です

**Comment by k0kubun** [comment]
これjとk押してるだけなんですけど、画面の外に出そうになったら勝手に画面がスクロールするので、実装しようとしている挙動だと青くなってるツイートが画面外に出ることはないはずなんですよね

![a](https://cloud.githubusercontent.com/assets/3138447/13780149/86cf4cac-eb01-11e5-8e92-0aaac7f28041.gif)

**Comment by akawshi** [comment]
その機能について理解しましたが, 実際そうならないんですよね...

**Comment by k0kubun** [comment]
今日きづきましたがこっちも32ビット環境で起きうるバグな気がします。
v0.3.0では直ってる可能性があるんですがどうでしょうか。
https://github.com/k0kubun/Nocturn/releases/tag/v0.3.0

**Comment by akawshi** [comment]
こちらもスクロールの動作を確認しました
修正ありがとうございます

**Comment by k0kubun** [comment]
よかったです!
