### ISSUE TITLE
nocturn flagged as malware by VirusTotal

### ISSUE THREAD

**Issue by core-code** [k0kubun/Nocturn#92]
https://www.virustotal.com/gui/file/5ec4c8d1e209d2a2f10d46ea8b4e0f16ddcdc28bebb76affba55560d7dfb3a2d/detection

any ideas?

**Comment by k0kubun** [comment]
No. What should I fix?

**Comment by core-code** [comment]
i guess the normal procedure is to get into contact with the virus scanner vendors that are flagging you

**Comment by k0kubun** [comment]
I think this was related to usage of old Electron, so I upgraded it to a fairly new version. Please try v1.8.3.

**Comment by core-code** [comment]
all green thanks: 
https://www.virustotal.com/gui/file/6b0c23c5c62003d724923efc36d7f51e6655ce6ac8c9e6d98bb39c49c4abc2da/detection
